name: App Service Code

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  APPLICATION_PUBLISH_PROFILE: ${{ secrets.PUBLISH_PROFILE }}
  AZURE_WEBAPP_NAME: dinno-app

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "yarn"

      - name: Install dependencies and build
        run: |
          yarn install --no-lockfile
          yarn build
          mv ./build/static ./build/standalone/build
          mv ./public ./build/standalone

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: dinno-app  # Ensure this matches the name used in download-artifact
          path: ./build/standalone
          retention-days: 5  # Keep the artifact for 5 days

  deploy:
    runs-on: ubuntu-latest
    needs: build

    environment:
      name: production
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: dinno-app  # Ensure this matches the uploaded artifact name
          path: ./build/standalone

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          slot-name: "Production"
          package: ./build/standalone
